// CleanTrack Nashik - System Constants & Civic Master Data

export const NASHIK_COORDINATES = {
  center: {
    lat: 19.9975,
    lng: 73.7898,
  },
  bounds: {
    minLat: 19.85,
    maxLat: 20.12,
    minLng: 73.68,
    maxLng: 73.92,
  },
};

export const NASHIK_ZONES = [
  {
    code: 'PANCHAVATI',
    name: 'Panchavati Zone',
    nameMarathi: 'पंचवटी विभाग',
    wardCount: 6,
    centerLatitude: 20.0125,
    centerLongitude: 73.7995,
    officeAddress: 'Panchavati Divisional Office, Makhmalabad Naka, Nashik',
    emergencyContact: '0253-2512010',
    localities: ['Ramkund', 'Tapovan', 'Dindori Road', 'Makhmalabad', 'Panchavati Karanja', 'Mhasrul', 'Adgaon'],
  },
  {
    code: 'NASHIK_WEST',
    name: 'Nashik West Zone',
    nameMarathi: 'नाशिक पश्चिम विभाग',
    wardCount: 5,
    centerLatitude: 19.9995,
    centerLongitude: 73.7655,
    officeAddress: 'West Divisional Office, Rajiv Gandhi Bhavan, Gangapur Road, Nashik',
    emergencyContact: '0253-2575631',
    localities: ['College Road', 'Gangapur Road', 'Mahatma Nagar', 'Old Gangapur Naka', 'Canada Corner', 'Trimbak Naka'],
  },
  {
    code: 'NASHIK_EAST',
    name: 'Nashik East Zone',
    nameMarathi: 'नाशिक पूर्व विभाग',
    wardCount: 6,
    centerLatitude: 19.9882,
    centerLongitude: 73.7998,
    officeAddress: 'East Divisional Office, Dwarka Circle, Nashik',
    emergencyContact: '0253-2591244',
    localities: ['Dwarka', 'Mumbai Naka', 'Shalimar', 'Bytco Point', 'Ganeshnagar', 'Katadewadi', 'Upnagar'],
  },
  {
    code: 'CIDCO',
    name: 'CIDCO / New Nashik Zone',
    nameMarathi: 'सिडको / नवीन नाशिक विभाग',
    wardCount: 7,
    centerLatitude: 19.965,
    centerLongitude: 73.755,
    officeAddress: 'New Nashik Divisional Office, Untwadi Road, CIDCO, Nashik',
    emergencyContact: '0253-2391055',
    localities: ['Untwadi', 'Uttamnagar', 'Pawan Nagar', 'Ambad Link Road', 'Trimurti Chowk', 'Chetana Nagar'],
  },
  {
    code: 'SATPUR',
    name: 'Satpur Zone',
    nameMarathi: 'सातपूर विभाग',
    wardCount: 5,
    centerLatitude: 19.982,
    centerLongitude: 73.725,
    officeAddress: 'Satpur Divisional Office, MIDC Main Road, Satpur, Nashik',
    emergencyContact: '0253-2351280',
    localities: ['Satpur MIDC', 'Ashoknagar', 'Trimbak Road', 'Shramik Nagar', 'Parijat Nagar', 'Mahatmanagar Extension'],
  },
  {
    code: 'NASHIK_ROAD',
    name: 'Nashik Road Zone',
    nameMarathi: 'नाशिक रोड विभाग',
    wardCount: 6,
    centerLatitude: 19.9555,
    centerLongitude: 73.8385,
    officeAddress: 'Nashik Road Divisional Office, Near Railway Station, Nashik Road',
    emergencyContact: '0253-2461022',
    localities: ['Railway Station Area', 'Jail Road', 'Deolali Gaon', 'Subhash Road', 'Datta Mandir', 'Sinnar Phata'],
  },
];

export const CIVIC_CATEGORIES = [
  {
    code: 'GARBAGE',
    name: 'Garbage & Waste',
    nameMarathi: 'कचरा व घनकचरा',
    icon: 'Trash2',
    description: 'Overflowing bins, uncollected waste, illegal roadside garbage',
    defaultSlaHours: 24,
    subcategories: [
      { name: 'Garbage not collected from doorstep/bin', nameMarathi: 'घरोघरी/कुंडीतून कचरा उचलला नाही' },
      { name: 'Garbage dumped on open road/plot', nameMarathi: 'रस्त्यावर किंवा मोकळ्या जागेत कचरा टाकला' },
      { name: 'Overflowing community garbage bin', nameMarathi: 'कचराकुंडी ओसंडून वाहत आहे' },
      { name: 'Construction & demolition waste debris', nameMarathi: 'बांधकाम राडारोडा / डेब्रिज' },
      { name: 'Commercial market waste accumulation', nameMarathi: 'बाजारपेठेतील कचरा' },
    ],
  },
  {
    code: 'ROADS',
    name: 'Road Damage & Potholes',
    nameMarathi: 'रस्ता व खड्डे',
    icon: 'Truck',
    description: 'Potholes, damaged asphalt, dangerous road sinkholes',
    defaultSlaHours: 48,
    subcategories: [
      { name: 'Dangerous pothole on main road', nameMarathi: 'मुख्य रस्त्यावरील धोकादायक खड्डा' },
      { name: 'Uneven / cracked road surface', nameMarathi: 'रस्त्याचा पृष्ठभाग खराब झाला आहे' },
      { name: 'Water-logged pothole zone', nameMarathi: 'खड्ड्यात पाणी साचून झालेली समस्या' },
      { name: 'Missing or broken speed breaker', nameMarathi: 'स्पीड ब्रेकर तुटलेला / नसलेला' },
      { name: 'Road digging without restoration', nameMarathi: 'खोदलेला रस्ता पूर्ववत न करणे' },
    ],
  },
  {
    code: 'DRAINAGE',
    name: 'Drainage & Manhole',
    nameMarathi: 'ड्रेनेज व गटार',
    icon: 'Droplets',
    description: 'Open manholes, blocked gutters, clogged storm drains',
    defaultSlaHours: 24,
    subcategories: [
      { name: 'Open / missing manhole cover (Hazard)', nameMarathi: 'उघडे किंवा तुटलेले मॅनहोल झाकण (धोकादायक)' },
      { name: 'Blocked drainage causing backflow', nameMarathi: 'गटार तुंबून दुर्गंधी व घाण पाणी' },
      { name: 'Damaged chamber or storm water drain', nameMarathi: 'पावसाळी गटार / चेंबर तुटले आहे' },
      { name: 'Mosquito breeding in stagnant drain', nameMarathi: 'साचलेल्या पाण्यात डासांची पैदास' },
    ],
  },
  {
    code: 'WATER_LEAKAGE',
    name: 'Water Supply Leakage',
    nameMarathi: 'पाणीपुरवठा गळती',
    icon: 'Waves',
    description: 'Burst pipelines, contaminated water, low municipal pressure',
    defaultSlaHours: 12,
    subcategories: [
      { name: 'Drinking water pipeline burst / major leak', nameMarathi: 'पिण्याच्या पाण्याची मुख्य पाईपलाईन फुटली' },
      { name: 'Roadside municipal valve leakage', nameMarathi: 'रस्त्यावरील व्हॉल्व्हमधून पाण्याची नासाडी' },
      { name: 'Contaminated / muddy drinking water', nameMarathi: 'गढूळ किंवा दूषित पाणीपुरवठा' },
      { name: 'No water supply during scheduled hours', nameMarathi: 'वेळेवर पाणीपुरवठा न होणे' },
    ],
  },
  {
    code: 'STREETLIGHT',
    name: 'Streetlight Issues',
    nameMarathi: 'पथदिवे (स्ट्रीटलाईट)',
    icon: 'Lightbulb',
    description: 'Non-functioning streetlights, exposed electric wires',
    defaultSlaHours: 24,
    subcategories: [
      { name: 'Streetlight pole not turning on at night', nameMarathi: 'रात्रीच्या वेळी पथदिवा बंद असणे' },
      { name: 'Entire street / lane in darkness', nameMarathi: 'संपूर्ण गल्लीतील दिवे बंद असणे' },
      { name: 'Exposed live wiring near pole base', nameMarathi: 'खांबाजवळील उघड्या विजेच्या तारा (धोका)' },
      { name: 'Streetlights remaining on during day', nameMarathi: 'दिवसाही पथदिवे सुरू राहणे' },
    ],
  },
  {
    code: 'PUBLIC_TOILET',
    name: 'Public Toilet Facility',
    nameMarathi: 'सार्वजनिक शौचालय',
    icon: 'Bath',
    description: 'Filthy public restrooms, water shortage, broken doors',
    defaultSlaHours: 24,
    subcategories: [
      { name: 'Extremely unhygienic / not cleaned', nameMarathi: 'अस्वच्छता व घाणीचे साम्राज्य' },
      { name: 'No water supply in community toilet', nameMarathi: 'शौचालयात पाणी उपलब्ध नाही' },
      { name: 'Broken door, lock or tap fixtures', nameMarathi: 'दरवाजे, कड्या किंवा नळ तुटलेले' },
      { name: 'Septic tank overflow', nameMarathi: 'सेप्टिक टँक ओसंडून वाहणे' },
    ],
  },
  {
    code: 'FOOTPATH',
    name: 'Footpath & Walkway',
    nameMarathi: 'पादचारी मार्ग / फुटपाथ',
    icon: 'Footprints',
    description: 'Encroached walkways, broken paving blocks, missing kerbstones',
    defaultSlaHours: 72,
    subcategories: [
      { name: 'Broken / missing footpath paver blocks', nameMarathi: 'फुटपाथचे पेव्हर ब्लॉक्स तुटलेले' },
      { name: 'Encroachment blocking pedestrian path', nameMarathi: 'फुटपाथवर अतिक्रमण / अडथळा' },
      { name: 'Dangerous open trench along footpath', nameMarathi: 'फुटपाथ लगत धोकादायक खड्डा' },
    ],
  },
  {
    code: 'SEWAGE_OVERFLOW',
    name: 'Sewage Overflow',
    nameMarathi: 'सांडपाणी ओसंडणे',
    icon: 'AlertTriangle',
    description: 'Sewage running on public roads, foul odor, contamination',
    defaultSlaHours: 12,
    subcategories: [
      { name: 'Raw sewage overflowing on public street', nameMarathi: 'रस्त्यावर सांडपाणी वाहत आहे' },
      { name: 'Choked underground sewer line', nameMarathi: 'भूमिगत गटार लाईन चोक-अप' },
      { name: 'Severe foul odor affecting residents', nameMarathi: 'तीव्र दुर्गंधी व आरोग्यास धोका' },
    ],
  },
  {
    code: 'ILLEGAL_DUMPING',
    name: 'Illegal Dumping',
    nameMarathi: 'बेकायदेशीर कचरा टाकणे',
    icon: 'ShieldAlert',
    description: 'Commercial hazardous dumping, burning plastic waste',
    defaultSlaHours: 24,
    subcategories: [
      { name: 'Open burning of plastic and dry garbage', nameMarathi: 'प्लास्टिक किंवा कचरा उघड्यावर जाळणे' },
      { name: 'Industrial or chemical waste dumping', nameMarathi: 'औद्योगिक किंवा रासायनिक कचरा टाकणे' },
      { name: 'Debris dumped in Godavari river bed', nameMarathi: 'गोदावरी नदीपात्रात कचरा/डेब्रिज फेकणे' },
    ],
  },
  {
    code: 'STRAY_ANIMALS',
    name: 'Stray Animal / Dead Animal',
    nameMarathi: 'भटके / मृत प्राणी समस्या',
    icon: 'PawPrint',
    description: 'Aggressive stray packs, dead animal removal urgent dispatch',
    defaultSlaHours: 12,
    subcategories: [
      { name: 'Urgent dead animal removal on public road', nameMarathi: 'रस्त्यावरील मृत प्राण्याची विल्हेवाट (तातडीने)' },
      { name: 'Aggressive stray dogs biting / chasing', nameMarathi: 'आक्रमक भटके कुत्रे / चावण्याचा धोका' },
      { name: 'Cattle causing traffic blockage on road', nameMarathi: 'रस्त्यावरील भटक्या जनावरांमुळे वाहतूक कोंडी' },
    ],
  },
  {
    code: 'TREE_FALLEN',
    name: 'Tree / Branch Hazard',
    nameMarathi: 'झाड पडणे / धोकादायक फांदी',
    icon: 'Trees',
    description: 'Fallen trees on road, hazardous dried branches over electric wires',
    defaultSlaHours: 12,
    subcategories: [
      { name: 'Fallen tree blocking public road/traffic', nameMarathi: 'झाड पडून रस्ता / वाहतूक बंद झाली आहे' },
      { name: 'Dangerous branch hanging over electric wires', nameMarathi: 'विद्युत तारांवर लोंबकळणारी धोकादायक फांदी' },
      { name: 'Dry tree prone to falling during rains', nameMarathi: 'सुकलेले झाड कोसळण्याचा धोका' },
    ],
  },
  {
    code: 'OTHER',
    name: 'Other Civic Issues',
    nameMarathi: 'इतर नागरी समस्या',
    icon: 'HelpCircle',
    description: 'Public property damage, open pits, missing municipal signage',
    defaultSlaHours: 72,
    subcategories: [
      { name: 'Public property or park infrastructure damaged', nameMarathi: 'सार्वजनिक उद्यानातील साहित्य नादुरुस्त' },
      { name: 'Missing or vandalized municipal road signboard', nameMarathi: 'रस्त्यावरील दिशादर्शक फलक गायब / तुटलेला' },
      { name: 'General civic nuisance', nameMarathi: 'इतर सामान्य नागरी तक्रार' },
    ],
  },
];

export const STATUS_CONFIG: Record<
  string,
  {
    label: string;
    labelMarathi: string;
    color: string;
    badgeBg: string;
    badgeText: string;
    borderColor: string;
    description: string;
  }
> = {
  SUBMITTED: {
    label: 'Submitted',
    labelMarathi: 'नोंदणी झाली',
    color: '#0284c7',
    badgeBg: 'bg-sky-50',
    badgeText: 'text-sky-700',
    borderColor: 'border-sky-300',
    description: 'Complaint successfully received in CleanTrack portal.',
  },
  RECEIVED: {
    label: 'Received',
    labelMarathi: 'स्वीकृत',
    color: '#6366f1',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-700',
    borderColor: 'border-indigo-300',
    description: 'Acknowledged by the system and queued for triage.',
  },
  UNDER_REVIEW: {
    label: 'Under Review',
    labelMarathi: 'तपासणी सुरू',
    color: '#f59e0b',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-800',
    borderColor: 'border-amber-300',
    description: 'Divisional officer is verifying location and category.',
  },
  ASSIGNED: {
    label: 'Assigned',
    labelMarathi: 'विभागास नियुक्त',
    color: '#8b5cf6',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-700',
    borderColor: 'border-purple-300',
    description: 'Dispatched to responsible department and field crew.',
  },
  IN_PROGRESS: {
    label: 'In Progress',
    labelMarathi: 'काम सुरू आहे',
    color: '#ea580c',
    badgeBg: 'bg-orange-50',
    badgeText: 'text-orange-700',
    borderColor: 'border-orange-300',
    description: 'Ground crew has commenced work at the site.',
  },
  RESOLVED: {
    label: 'Resolved',
    labelMarathi: 'निवारण झाले',
    color: '#16a34a',
    badgeBg: 'bg-green-50',
    badgeText: 'text-green-700',
    borderColor: 'border-green-300',
    description: 'Issue reported resolved by team. Awaiting citizen confirmation.',
  },
  CLOSED: {
    label: 'Closed',
    labelMarathi: 'बंद केले',
    color: '#475569',
    badgeBg: 'bg-slate-100',
    badgeText: 'text-slate-700',
    borderColor: 'border-slate-300',
    description: 'Citizen confirmed resolution. Ticket successfully closed.',
  },
  REOPENED: {
    label: 'Reopened',
    labelMarathi: 'पुन्हा उघडले',
    color: '#dc2626',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-700',
    borderColor: 'border-rose-300',
    description: 'Citizen indicated problem persists. Escalated for rework.',
  },
  REJECTED: {
    label: 'Rejected',
    labelMarathi: 'नाकारले',
    color: '#991b1b',
    badgeBg: 'bg-red-50',
    badgeText: 'text-red-700',
    borderColor: 'border-red-300',
    description: 'Issue is outside civic jurisdiction or violates terms.',
  },
  DUPLICATE: {
    label: 'Duplicate',
    labelMarathi: 'आधीच नोंदवलेली',
    color: '#64748b',
    badgeBg: 'bg-gray-100',
    badgeText: 'text-gray-700',
    borderColor: 'border-gray-300',
    description: 'Already tracked under another reference ID.',
  },
  INVALID_LOCATION: {
    label: 'Invalid Location',
    labelMarathi: 'अवैध ठिकाण',
    color: '#b45309',
    badgeBg: 'bg-yellow-50',
    badgeText: 'text-yellow-800',
    borderColor: 'border-yellow-300',
    description: 'Coordinates provided fall outside Nashik service area.',
  },
  MORE_INFORMATION_REQUIRED: {
    label: 'More Info Needed',
    labelMarathi: 'अधिक माहिती आवश्यक',
    color: '#0891b2',
    badgeBg: 'bg-cyan-50',
    badgeText: 'text-cyan-700',
    borderColor: 'border-cyan-300',
    description: 'Officer requested clearer landmark or additional photo.',
  },
};
